---
# tasks file for dnscrypt + pihole setup
# https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0
# https://github.com/DNSCrypt/dnscrypt-proxy/wiki

# print architecture info: $uname -sm (Linux armv7l)

- name: Download dnscrypt-proxy release 2.1.1
  ansible.builtin.shell: |
    curl -SL -O https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.1/dnscrypt-proxy-linux_arm-2.1.1.tar.gz
    tar xzvf dnscrypt-proxy-linux_arm-2.1.1.tar.gz
    mv linux-arm dnscrypt-proxy
    rm dnscrypt-proxy-linux_arm-2.1.1.tar.gz
  args:
    chdir: /opt
  
- name: Configure dnscrypt-proxy
  ansible.builtin.template:
    src: templates/dnscrypt-proxy.toml.j2
    dest: /opt/dnscrypt-proxy/dnscrypt-proxy.toml

- name: Install dnscrypt-proxy service
  become: true
  ansible.builtin.shell: |
    /opt/dnscrypt-proxy/dnscrypt-proxy -service install
    /opt/dnscrypt-proxy/dnscrypt-proxy -service start
