---
# tasks file for dnscrypt + pihole setup
# https://github.com/pi-hole/pi-hole/wiki/DNSCrypt-2.0
# https://github.com/DNSCrypt/dnscrypt-proxy/wiki

# print architecture info: $uname -sm (Linux armv7l)
- name: Download dnscrypt-proxy release 2.1.1
  ansible.builtin.get_url:
    url: https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.1/dnscrypt-proxy-linux_arm-2.1.1.tar.gz
    dest: /opt/dns/dnscrypt-proxy-linux_arm-2.1.1.tar.gz
    # checksum: sha256:x3434234234

- name: Extract dnscrypt-proxy release 2.1.1
  ansible.builtin.shell: |
    tar xzvf dnscrypt-proxy-linux_arm-2.1.1.tar.gz
    mv linux-arm dnscrypt-proxy
    rm dnscrypt-proxy-linux_arm-2.1.1.tar.gz
  args:
    chdir: /opt/dns

- name: Fix permissions for dnscrypt /config bound dir  
  become: true
  ansible.builtin.shell: |
    chmod -R 777 /opt/dns/dnscrypt-proxy
  
- name: Configure dnscrypt-proxy
  ansible.builtin.template:
    src: templates/dnscrypt-proxy.toml.j2
    dest: /opt/dns/dnscrypt-proxy/dnscrypt-proxy.toml
    owner: pi
    group: docker

# Not required when dockerizing dnscrypt-proxy
# - name: Install dnscrypt-proxy service
#   become: true
#   ansible.builtin.shell: |
#     /opt/dnscrypt-proxy/dnscrypt-proxy -service install
#     /opt/dnscrypt-proxy/dnscrypt-proxy -service start
