---
# Tasks for installing docker and docker-compose on debian systems (including raspberry pi OS)

## Install Docker
## https://docs.docker.com/engine/install/debian
- name: Create gpg key dir
  become: true
  ansible.builtin.shell: mkdir -p /etc/apt/keyrings

- name: Add Docker GPG apt key
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Add Docker Repository
  ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Run apt update to update repo lists used for installing packages
- name: Run "apt-get update"
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker from repository
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

- name: Add PIHOLE_USER to docker group
  become: true
  ansible.builtin.shell: usermod -aG docker '{{ lookup("env", "PIHOLE_USER") }}'

- name: Enable and start Docker systemd service
  ansible.builtin.shell: |
    sudo systemctl enable docker.service
    sudo systemctl start docker.service

## Install docker-compose
- name: Downloading binary for docker-compose 
  ansible.builtin.shell: |
    curl -SL https://github.com/docker/compose/releases/download/v2.8.0/docker-compose-linux-armv7 -o /usr/bin/docker-compose
    chmod +x /usr/bin/docker-compose 