---
# tasks file for docker
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#commonly-used-facts

- name: Install docker, conditional debian distro 
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Install docker, conditional debian distro 
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
