---

# klutchell/dnscrypt-proxy requires DOCKER_BUILDKIT
- name: Enable DOCKER_BUILDKIT for docker and docker-compose on PiHole hosts
  ansible.builtin.shell: |
    echo "export DOCKER_BUILDKIT=1" >> $HOME/.bashrc
    echo "export COMPOSE_DOCKER_CLI_BUILD=1" >> $HOME/.bashrc
    source $HOME/.bashrc

- name: Process docker-compose.yml file for pihole server
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: /opt/dns/docker-compose.yml
    mode: '0755'

# - name: Process docker-compose.yml file for traefik
#   ansible.builtin.template:
#     src: templates/docker-compose.traefik.yml.j2
#     dest: /opt/dns/docker-compose.traefik.yml
#     mode: '0755'

# - name: Process docker-compose.yml file for pihole
#   ansible.builtin.template:
#     src: templates/docker-compose.pihole.yml.j2
#     dest: /opt/dns/docker-compose.pihole.yml
#     mode: '0755'