---
- name: Process docker-compose.yml file for pihole server
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: /opt/dns/docker-compose.yml
    mode: '0755'

# - name: Process docker-compose.yml file for traefik
#   ansible.builtin.template:
#     src: templates/docker-compose.traefik.yml.j2
#     dest: /opt/dns/docker-compose.traefik.yml
#     mode: '0755'

# - name: Process docker-compose.yml file for pihole
#   ansible.builtin.template:
#     src: templates/docker-compose.pihole.yml.j2
#     dest: /opt/dns/docker-compose.pihole.yml
#     mode: '0755'